import SwiftUI

struct SimpleSummaryView: View {
    let article: Article
    @Environment(\.dismiss) private var dismiss
    
    var body: some View {
        ZStack {
            Color.laymanCream.ignoresSafeArea()
            
            ScrollView(.vertical, showsIndicators: false) {
                VStack(alignment: .leading, spacing: 24) {
                    // Headline
                    Text(article.laymanTitle.isEmpty ? article.title : article.laymanTitle)
                        .font(.system(size: 28, weight: .bold))
                        .foregroundColor(.laymanDark)
                        .lineSpacing(4)
                        .fixedSize(horizontal: false, vertical: true)
                        .padding(.top, 20)
                    
                    // Image (if available)
                    if let imageURL = article.imageURL, let url = URL(string: imageURL) {
                        AsyncImage(url: url) { phase in
                            switch phase {
                            case .success(let image):
                                image
                                    .resizable()
                                    .aspectRatio(contentMode: .fill)
                                    .frame(maxWidth: .infinity)
                                    .frame(height: 200)
                                    .clipped()
                                    .cornerRadius(16)
                            default:
                                EmptyView()
                            }
                        }
                    }
                    
                    // Content: Either the cards or a shimmer skeleton
                    if article.laymanCards.isEmpty {
                        // Shimmer loading state
                        VStack(alignment: .leading, spacing: 28) {
                            ForEach(0..<3, id: \.self) { i in
                                VStack(alignment: .leading, spacing: 12) {
                                    HStack(spacing: 8) {
                                        Circle()
                                            .fill(Color.laymanLightGray.opacity(0.3))
                                            .frame(width: 8, height: 8)
                                        SkeletonLine(width: 60, height: 10)
                                    }
                                    SkeletonLine()
                                    SkeletonLine()
                                    SkeletonLine(width: 200)
                                }
                            }
                        }
                    } else {
                        // Real content
                        VStack(alignment: .leading, spacing: 28) {
                            ForEach(Array(article.laymanCards.enumerated()), id: \.offset) { index, card in
                                VStack(alignment: .leading, spacing: 12) {
                                    HStack(spacing: 8) {
                                        Circle()
                                            .fill(Color.laymanOrange)
                                            .frame(width: 8, height: 8)
                                        
                                        Text("POINT \(index + 1)")
                                            .font(LaymanFont.small(11))
                                            .tracking(1.0)
                                            .foregroundColor(.laymanGray)
                                    }
                                    
                                    Text(card)
                                        .font(.system(size: 19, weight: .regular))
                                        .lineSpacing(8)
                                        .foregroundColor(.laymanDark.opacity(0.9))
                                        .fixedSize(horizontal: false, vertical: true)
                                }
                            }
                        }
                    }
                    
                    // Footer
                    VStack(spacing: 20) {
                        Divider().opacity(0.3)
                        
                        Text("This summary was generated by Layman to provide a clear, jargon-free overview of the news.")
                            .font(LaymanFont.caption(13))
                            .foregroundColor(.laymanGray)
                            .multilineTextAlignment(.center)
                            .padding(.horizontal, 20)
                    }
                    .padding(.top, 20)
                    
                    Spacer(minLength: 60)
                }
                .padding(.horizontal, 24)
            }
        }
        .navigationBarTitleDisplayMode(.inline)
        .navigationBarBackButtonHidden(true)
        .toolbar {
            ToolbarItem(placement: .navigationBarLeading) {
                Button {
                    dismiss()
                } label: {
                    HStack(spacing: 4) {
                        Image(systemName: "chevron.left")
                            .font(.system(size: 14, weight: .semibold))
                        Text("Back")
                            .font(LaymanFont.headline(16))
                    }
                    .foregroundColor(.laymanDark)
                    .padding(.horizontal, 12)
                    .padding(.vertical, 8)
                    .background(Color.laymanBeige.opacity(0.6))
                    .clipShape(Capsule())
                }
            }
            
            ToolbarItem(placement: .principal) {
                Text("Simple Summary")
                    .font(LaymanFont.logo(18))
                    .foregroundColor(.laymanDark)
            }
        }
    }
}
